# Generated by Django 5.2 on 2025-04-05 23:36

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagediagnostic',
            name='image',
            field=models.ImageField(max_length=255, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='diagnostic_images/'),
        ),
    ]
